Wheel speed function optimized
GryphonRacingFSAE/VCU-Firmware pull request #14
Opened 2024-03-14 15:58 UTC by riyan-noaman

# TASK TITLE

Lowering use of repetitive tasks and variables in order to create efficiency

## Changes

majority of wheel speed variables omitted and replaced with arrays
using for loops rather then high numbers of if else statements

## Deployment

- Bullet list of changes to deployment 

## Proof of functionality (screenshot, logs, etc)

yet to be tested 

## Additional Notes

Code will not work in current condition, missing checks for TIM3 channels, will be added later tdy then tested

## Checklist

- [ ] Your code builds clean without any errors or warnings
- [ ] Code has been formatted (clang-format, cmake-format, black, prettier, rustfmt, etc)
- [ ] Where possible, unit tests have been added
- [ ] Code is well-commented & understood

2024-03-14 16:20 UTC, Nomalah requested changes
Go through, re-read the style guide. Put the results of the process into CTRL_Data. Also, remove comments which are stupid and self describing. Ex. "Loop from 0 to NUM_WHEELS"

2024-03-15 01:58 UTC, Nomalah approved these changes
Style guide and comment points again.

2024-03-15 01:58 UTC, Nomalah commented on Core/Inc/control.h
> +#define numTeeth 32;
```suggestion
#define NUM_TEETH 32;
```
Remember the style guide

2024-03-15 01:58 UTC, Nomalah commented on Core/Src/control.c
> +
Remove this debug printing or replace it with a TRACE_PRINT
```suggestion
```

2024-03-15 01:58 UTC, Nomalah commented on Core/Src/control.c
> +void ManageTimerOverflow(TIM_HandleTypeDef * htim) {
```suggestion
void manageWheelSpeedTimerOverflow(const TIM_HandleTypeDef * htim) {
```
Watch the style guide, and if you name it better, you don't need the comment describing what the function does.

2024-03-15 01:58 UTC, Nomalah commented on Core/Src/control.c
>   * Called when an input capture event occurs
This comment block should be moved elsewhere & updated to represent the current status of the code. It should not describe exactly what the code does. Comments should not describe what something does (unless it's not obvious), comments should describe *why* something is done.

2024-03-15 01:58 UTC, Nomalah commented on Core/Src/control.c
>  }
Remove like 99% of these comments. "store timer value within rising edge variable" is a pointless comments.
Don't comment what you changed, that's what git is for.

2024-03-15 01:59 UTC, Nomalah requested changes
I actually wanted to request changes

2024-03-15 01:59 UTC, Nomalah requested changes
I actually wanted to request changes

2024-03-21 18:01 UTC, Nomalah requested changes
Undo the formatting changes made for BSPC, and add documentation on the wheel speed sensors in the readme (include the datasheet and the mapping from wss to stm32 pin/timer).

2024-03-21 18:01 UTC, Nomalah commented on Core/Src/control.c
>  	}
Can you do a quick check of the formatting?

2024-03-21 19:11 UTC, Nomalah commented
If you can add the equations used to reach the correct prescalers & auto reload value for each timer into the readme as LaTeX equations that would be great.

2024-03-22 04:20 UTC, riyan-noaman commented
merge conflicts need to be resolved again incorrect resolutions were used the first time

2024-03-22 04:55 UTC, Nomalah approved these changes
LGTM

2024-03-22 04:56 UTC, merged