pump control
GryphonRacingFSAE/VCU-Firmware pull request #16
Opened 2024-03-21 00:57 UTC by riyan-noaman

fix: pwm is outputting proper frequencies

# TASK TITLE

Brief description of task goals

## Changes

- Added pwm control to PE9 using TIM1
- TIM1 is no longer system clock (TIM8 is now in that position)
- Added functions for each state of the pump control (no need for a wake up state since the pulses are set to be long enough to wake the pump up)

## Additional Notes

pump has been tested and is deemed to be working properly

## Checklist

- [ ] Your code builds clean without any errors or warnings
- [ ] Code has been formatted (clang-format, cmake-format, black, prettier, rustfmt, etc)
- [ ] Where possible, unit tests have been added
- [ ] Code is well-commented & understood

2024-03-21 05:26 UTC, Nomalah requested changes
Looks good, just a few things. Make sure to add the datasheet for the pump & pwm info to the readme and by the pumpCtrl function.

2024-03-21 05:26 UTC, Nomalah commented on APPS_FW_22.ioc
> +TIM4.Prescaler=256-1
Could you undo the changes made to TIM3 and TIM4? This may cause issues when we merge in Ronak's branch.

2024-03-21 05:26 UTC, Nomalah commented on Core/Inc/control.h
> +#define INPUT_POWER 8
This isn't being used. What is this for?
```suggestion
```

2024-03-21 05:26 UTC, Nomalah commented on Core/Src/main.c
> +  //HAL_TIM_PWM_Start(&htim1, TIM_CHANNEL_1);
```suggestion
```
No longer used.

2024-03-21 05:26 UTC, Nomalah commented on Core/Src/control.c
> +}
The alternate functions don't really seem useful here. Consider convertint this function to taking a % input. that would be useful later on. 
![image](https://github.com/GryphonRacingFSAE/VCU-Firmware/assets/36043275/6e18bdfe-bb22-4bf0-9a03-1f1a2878392a)
Maybe force 0% to 10% duty cycle and 100% to 90% duty cycle, and then interpolate the remaining values from 13% to 85%?

2024-03-21 05:26 UTC, Nomalah commented on Core/Src/control.c
> +	pumpCycle(4);
If we're going to just set it once, I'd say to just run the function at the start of the task (before the loop)

2024-03-21 05:26 UTC, Nomalah requested changes
Looks good, just a few things. Make sure to add the datasheet for the pump & pwm info to the readme and by the pumpCtrl function.

2024-03-21 05:27 UTC, riyan-noaman commented on Core/Inc/control.h
> +#define INPUT_POWER 8
from old version forgot to remove will do rn

2024-03-21 05:28 UTC, riyan-noaman commented on APPS_FW_22.ioc
> +TIM4.Prescaler=256-1
yeah for sure

2024-03-21 05:30 UTC, riyan-noaman commented on Core/Src/control.c
> +	pumpCycle(4);
mainly put this in the pumpCtrl function to show how we could call it in there in the future if we wanted to add cases based on temperatures or anything but we can put it in the task if we're just planning on running one mode

2024-03-21 05:53 UTC, riyan-noaman commented on Core/Src/control.c
> +}
I don't understand this one, do you mean something like:
case 1 (covers 0 - 10% ie motor is stopped)
case 2 (covers 13-85%)
case 3 (86-97%)

so if i take the average value for the pulse (CCR) and input it into each case it should still cover that function of the motor

and switching the case values to the percentage value (1,2,10,50.....)  and then assuming intervals of 5 for each case so the cases look something like 

case 0:
case 1:
.
.
.
case 10:
ccr value updated 
break;
etc. 

?

2024-03-21 06:19 UTC, Nomalah commented on Core/Src/control.c
> +}
No cases at all, just take in the % requested and do something along the lines of the following:
```c++
if (percent == 0) {
	TIM1->CCR1 = // whatever 10% duty cycle is
} else if (percent == 100) {
	TIM1->CCR1 = // whatever 90% duty cycle is
} else {
	TIM1->CCR1 = // Map the 0-100 input to 13-85% duty cycle
}
```

2024-03-21 06:22 UTC, riyan-noaman commented on Core/Src/control.c
> +}
ohhhh ok thats simple will do, no need to ensure that values less than 13 and greater than  85 are not called correct?

2024-03-21 13:26 UTC, Nomalah commented on Core/Src/control.c
> +}
Yeah you're probably fine to ignore someone calling with like -1% or 110% requested

2024-03-21 19:10 UTC, Nomalah commented
If you can add the equations used to reach the 100Hz with given duty cycle into the readme as LaTeX equations that would be great.

2024-03-22 03:49 UTC, Nomalah approved these changes

2024-03-22 03:49 UTC, Nomalah approved these changes

2024-03-22 03:49 UTC, merged