wheel speed sensor !TEST VERSION!
GryphonRacingFSAE/VCU-Firmware pull request #8
Opened 2023-11-14 06:43 UTC by riyan-noaman

#Wheel speed Sensor
Brief description of task goals

## Changes

- Added needed header files to inc 
- Possibly fixed errors in APPS.c and Watchdog.h
- Commented out all references to Watchdog.c (unfinished, led to errors)
- Added wheelspeed sensor function into control task

## Deployment

- Bullet list of changes to deployment 

## Proof of functionality (screenshot, logs, etc)

## Additional Notes

- Ex. Structure of added code

## Checklist

- [ .] Your code builds clean without any errors or warnings
- [ ] Code has been formatted (clang-format, cmake-format, black, prettier, rustfmt, etc)
- [ ] Where possible, unit tests have been added
- [ .] Code is well-commented & understood

2023-11-28 20:33 UTC, m-verburg requested changes
I'd like to go over your implementation of the wheel speed measurement with you in more detail when you are available.

2023-11-28 20:33 UTC, m-verburg commented on Core/Src/control.c
> +	int circumference = 0.5;
Wrong data type, should be a float. Also when using integers, use specific width datatypes ie. int16_t

2023-11-28 20:33 UTC, m-verburg commented on Core/Src/control.c
> +//function for incrementing pulse count, as efficient as possible
Pins for wheel speed measuring were chosen specifically for the timer peripherals, using the timer will allow you to avoid triggering an interrupt for every pulse. Let me know when you are available and I can discuss this in more detail.

2024-02-17 02:34 UTC, Nomalah commented
Closed in favor of #9

2024-02-17 02:34 UTC, closed without merging